### ISSUE TITLE
Awesome 4.x port

### ISSUE THREAD

**Issue by samis** [copycat-killer/awesome-freedesktop#1]
This plguin does not work on Awesome 4.0 due to menu_gen.generate becoming async and taking a callback, and while I have tinkered a bit with the source I have failed to fix it myself. Using awesome with only the regular menubar works, but it would be nice to have a non-bar applications window.

**Comment by lcpz** [comment]
https://github.com/awesomeWM/awesome/issues/1365

**Comment by ghost** [comment]
If you want a temporary solution, [here](https://gist.github.com/BlueUsername/2e98525876fe9d3df139770715d07296) is my modified menu.lua which takes some extra arguments of items before and after the freedesktop menu and returns an awful.menu.

I've included a usage example down the bottom.

**Comment by lcpz** [comment]
At the current state, this is the best we can do.

When the [menubar refactoring](https://github.com/awesomeWM/awesome/issues/1365#issuecomment-271129290) will be complete, I'll update this module accordingly.

Thanks for the patch @BlueUsername .
