### ISSUE TITLE
Signals on a awful.menu

### ISSUE THREAD

**Issue by ducklin5** [copycat-killer/awesome-freedesktop#13]
I've been building on your Powerarrow Dark AwesomeWm config and I wanted to have a more dynamic menu. Its quite annoying having to click outside the menu for it to close. So I tried connecting the mouse leave signal to it. The config loads but the behavior doesn't change. Here is the code:
```
local builtmenu = freedesktop.menu.build({
	icon_size = beautiful.menu_height or 16,
	before = {
		{ "Awesome", myawesomemenu, beautiful.awesome_icon },
		-- other triads can be put here
	},
	after = {
		{ "Open terminal", terminal },
		-- other triads can be put here
	}
})

awful.util.mymainmenu = builtmenu
builtmenu:connect_signal("mouse::leave", function() awful.util.mymainmenu:toggle() end)
```
I'm not sure if  this is a bug or if menus just don't support signals. If its just not possible with signals, how else can I go about this?

**Comment by lcpz** [comment]
Every `awful.menu` has a `wibox`. You connect the signal to that.

```lua
awful.util.mymainmenu.wibox:connect_signal("mouse::leave", function()
    awful.util.mymainmenu:hide()
end)
```
