### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by zaoqi-unsafe** [copycat-killer/awesome-freedesktop#14]

**Comment by lcpz** [comment]
I'm sorry, I don't understand what you mean. Please elaborate.

**Comment by zaoqi-unsafe** [comment]
translation

**Comment by lcpz** [comment]
For categories, modify [here](https://github.com/awesomeWM/awesome/blob/master/lib/menubar/menu_gen.lua#L35-L56), for entries, read [this](https://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#localized-keys).

The first is dirty, the second is expensive, so you could fork and add a translation yourself. All you have to do is to translate table values [here](https://github.com/lcpz/awesome-freedesktop/blob/master/menu.lua#L93) and [here](https://github.com/lcpz/awesome-freedesktop/blob/master/menu.lua#L100).

I think it's not worth it and suggest you stick with English, but you suit yourself. Feel fee to do a PR.
