### ISSUE TITLE
luarocks version number invalid / out of date

### ISSUE THREAD

**Issue by alberdingk-thijm** [copycat-killer/awesome-freedesktop#15]
I'm on Void Linux and running awesome v4.3 and Lua 5.3.
Using `luarocks` 3.1.3 installed via `xbps-install`, I'm getting the following error when I run `sudo luarocks install awesome-freedesktop`:

```
Installing https://luarocks.org/awesome-freedesktop-git.rockspec

Error: /tmp/luarocks_luarocks-rockspec-awesome-freedesktop-git-2QIp89/awesome-freedesktop-git.rockspec: Type mismatch on field version: invalid value 'git' does not match '[%w.]+-[%d]+' (using rockspec format 1.0)
```

Looks like the simplest solution is to just assign a version number rather than "git".

**Comment by lcpz** [comment]
@aajjbb could you please maintain this one as well? Also, please check if lain rock is still valid. The [tag](https://github.com/lcpz/lain/blob/f1964b40e49dff92abdff97b7bd0408435ed589f/lain-scm-1.rockspec#L5) seems to have a typo by the way.

**Comment by aajjbb** [comment]
Hey there, I am sorry for the very late reply. I have just proposed #17 which should address this. Hope it helps.
