### ISSUE TITLE
Nil value (Upvalue capi)

### ISSUE THREAD

**Issue by eromatiya** [copycat-killer/awesome-freedesktop#18]
I recently discovered this project, but I got an error as seen on the screenshot below:  

![20191122_180350](https://user-images.githubusercontent.com/40349590/69416937-b6963c80-0d52-11ea-8905-c4d29a78e588.png)

Awesome version: awesome v4.3-530-g76f8c117 (Git-master branch)  
Lua Version: Lua 5.3.5

**Comment by lcpz** [comment]
Try dc0a18c.

**Comment by eromatiya** [comment]
It works now! Thanks!
