### ISSUE TITLE
Get rid of NixOS hardcoded applications path

### ISSUE THREAD

**Issue by pltanton** [copycat-killer/awesome-freedesktop#20]
Hi there!

Accidentally I [found](https://github.com/lcpz/awesome-freedesktop/blob/dc0a18c2c35a0cf888b5968115df810b90db91cf/menu.lua#L22), that for NixOS applications directory the path is hardcoded.

I can't find the reason why this fix is applied, but it seems to be outdated because NixOS support XDG out of the box now.; 
For example in my NixOS installation there is:
```
➜  ~ printenv | grep XDG_DATA
XDG_DATA_DIRS=/home/anton/.nix-profile/share:/etc/profiles/per-user/anton/share:/nix/var/nix/profiles/default/share:/run/current-system/sw/share
```
which already includes `.nix-profile/share`.

UPDATE:

I guess that the reason was here https://github.com/awesomeWM/awesome/commit/ea2c9deb68da7aa7f5aef30facd7c0c078269399 the menumar was not support XDG itself

**Comment by lcpz** [comment]
See #21.
